# Generated by Django 4.0.3 on 2022-03-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadorimrest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalite', models.CharField(max_length=100)),
                ('tpe_de_cart', models.CharField(max_length=100)),
                ('NNI', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
