# Generated by Django 4.0.3 on 2022-03-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadorimrest', '0003_remove_cart_name_remove_cart_nationalite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NNI', models.CharField(default='0000000', max_length=100)),
                ('Nom', models.CharField(default='0000000', max_length=100)),
                ('Prenom', models.CharField(default='0000000', max_length=100)),
                ('Sex', models.CharField(default='0000000', max_length=100)),
                ('date_naiss', models.CharField(default='0000000', max_length=100)),
                ('lieu_de_nai', models.CharField(default='0000000', max_length=100)),
                ('dateEmission', models.CharField(default='0000000', max_length=100)),
                ('dateValidie', models.CharField(default='0000000', max_length=100)),
                ('Pays', models.CharField(default='0000000', max_length=100)),
                ('Ville', models.CharField(default='0000000', max_length=100)),
                ('Rue', models.CharField(default='0000000', max_length=100)),
                ('codePostale', models.CharField(default='0000000', max_length=100)),
                ('typeDocument', models.CharField(default='0000000', max_length=100)),
                ('NumeroDocument', models.CharField(default='0000000', max_length=100)),
                ('Path', models.CharField(default='0000000', max_length=100)),
            ],
        ),
    ]
