# Generated by Django 4.0.3 on 2022-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadorimrest', '0004_passeport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='NNI',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Nom',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='NumeroDocument',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Path',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Pays',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Prenom',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Rue',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Sex',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Ville',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='codePostale',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='dateEmission',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='dateValidie',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_naiss',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='lieu_de_nai',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='typeDocument',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='NNI',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='Nom',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='NumeroDocument',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='Path',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='Pays',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='Prenom',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='Rue',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='Sex',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='Ville',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='codePostale',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='dateEmission',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='dateValidie',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='date_naiss',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='lieu_de_nai',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='passeport',
            name='typeDocument',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
