# Generated by Django 4.0.3 on 2022-03-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadorimrest', '0009_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackCart',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='FrCart',
        ),
        migrations.DeleteModel(
            name='PassePort',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
